# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1knrh90KIyU0CKD2a4KAdbDwz1OYCbM
"""

# !pip install docx2txt

######################### 1. find match
import docx2txt
import pandas as pd
import glob
import os
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Load resume
resume = docx2txt.process("Jos_cv.docx")

# Dynamically get all job files like J1.docx, J2.docx, ...
job_files = sorted(glob.glob("J*.docx"))

results = []

for job_file in job_files:
    # Load job description
    job_description = docx2txt.process(job_file)

    # Combine texts
    text = [resume, job_description]

    # Vectorize
    cv = CountVectorizer()
    count_matrix = cv.fit_transform(text)

    # Similarity score
    similarity = cosine_similarity(count_matrix)[0][1] * 100
    similarity = round(similarity, 2)

    # Clean job name (remove .docx)
    job_name = os.path.splitext(job_file)[0]

    results.append({
        "Job": job_name,
        "Match %": similarity
    })

# Create table
df = pd.DataFrame(results)

# Sort by best match
df = df.sort_values(by="Match %", ascending=False).reset_index(drop=True)

print(df)

################ 2. Re-do the resume to improve match to 95%
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

def get_keywords(job_text, top_n=25):
    tfidf = TfidfVectorizer(stop_words='english')
    X = tfidf.fit_transform([job_text])

    scores = X.toarray()[0]
    terms = tfidf.get_feature_names_out()

    top_idx = np.argsort(scores)[-top_n:][::-1]
    return [terms[i] for i in top_idx]

def inject_keywords(resume_text, keywords):
    injected = "\n\nCORE COMPETENCIES (JOB ALIGNED)\n"

    for k in keywords:
        injected += f"- Experience with {k}\n"

    return resume_text + injected

import glob
import docx2txt
from docx import Document

resume = docx2txt.process("Jos_cv.docx")
job_files = sorted(glob.glob("J*.docx"))

for job in job_files:
    job_text = docx2txt.process(job)

    keywords = get_keywords(job_text)

    boosted_resume = inject_keywords(resume, keywords)

    doc = Document()
    doc.add_heading(f"ATS Optimized Resume - {job}", 1)
    doc.add_paragraph(boosted_resume)

    output = f"ATS_{job}"
    doc.save(output)

    print("Created:", output)

#################### 3. Test new cv with job descriptions
import docx2txt
import pandas as pd
import glob
import os
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Load resume
resume = docx2txt.process("Jos_cv.docx")

# Dynamically get all job files like J1.docx, J2.docx, ...
job_files = sorted(glob.glob("ATS_J*.docx"))

results = []

for job_file in job_files:
    # Load job description
    job_description = docx2txt.process(job_file)

    # Combine texts
    text = [resume, job_description]

    # Vectorize
    cv = CountVectorizer()
    count_matrix = cv.fit_transform(text)

    # Similarity score
    similarity = cosine_similarity(count_matrix)[0][1] * 100
    similarity = round(similarity, 2)

    # Clean job name (remove .docx)
    job_name = os.path.splitext(job_file)[0]

    results.append({
        "Job": job_name,
        "Match %": similarity
    })

# Create table
df = pd.DataFrame(results)

# Sort by best match
df = df.sort_values(by="Match %", ascending=False).reset_index(drop=True)

print(df)

############## 4. Create cover letter for each job and resume
import glob
import docx2txt
from docx import Document
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import os

# ----------------------------
# READ FILE
# ----------------------------
def read_file(path):
    return docx2txt.process(path)

# ----------------------------
# KEYWORD EXTRACTION
# ----------------------------
def extract_keywords(text, top_n=12):
    tfidf = TfidfVectorizer(stop_words='english')
    X = tfidf.fit_transform([text])

    scores = X.toarray()[0]
    terms = tfidf.get_feature_names_out()

    top_idx = np.argsort(scores)[-top_n:][::-1]
    return [terms[i] for i in top_idx]

# ----------------------------
# COVER LETTER BUILDER
# ----------------------------
def build_cover_letter(candidate_name, job_name, resume_text, job_text, keywords):

    doc = Document()

    doc.add_heading(f"Cover Letter - {job_name}", 1)

    doc.add_paragraph(
        f"Dear Hiring Manager,\n\n"
        f"I am excited to apply for the {job_name} position. "
        f"My background, as reflected in my tailored resume, aligns closely with the requirements of this role."
    )

    doc.add_paragraph(
        "Based on the job description, I bring relevant experience in: "
        + ", ".join(keywords[:8]) + "."
    )

    doc.add_paragraph(
        "My attached resume highlights how I have applied these skills in practical settings, "
        "delivering results in operational efficiency, service quality, and team collaboration."
    )

    doc.add_paragraph(
        "I am confident that my experience and adaptability would allow me to contribute effectively to your organization."
    )

    doc.add_paragraph(
        "Thank you for your time and consideration. I look forward to the opportunity to discuss my application further.\n\n"
        f"Sincerely,\n{candidate_name}"
    )

    return doc

# ----------------------------
# LOAD FILES
# ----------------------------
ats_files = sorted(glob.glob("ATS_J*.docx"))
job_files = sorted(glob.glob("J*.docx"))

candidate_name = "Applicant"

# ----------------------------
# BUILD MAP: J1 ↔ ATS_J1
# ----------------------------
for ats_file in ats_files:

    job_id = ats_file.replace("ATS_", "").replace(".docx", "")
    job_file = f"{job_id}.docx"

    if not os.path.exists(job_file):
        print(f"Skipping {job_id} (no matching job file)")
        continue

    resume_text = read_file(ats_file)
    job_text = read_file(job_file)

    keywords = extract_keywords(job_text)

    doc = build_cover_letter(
        candidate_name,
        job_id,
        resume_text,
        job_text,
        keywords
    )

    output_file = f"cover_letter_{job_id}.docx"
    doc.save(output_file)

    print("Created:", output_file)







# !pip install python-docx

import glob
import os
import re
from collections import Counter
from docx import Document

# ----------------------------
# READ DOCX FILE
# ----------------------------
def read_docx(path):
    doc = Document(path)
    return "\n".join([p.text for p in doc.paragraphs])

# ----------------------------
# KEYWORD EXTRACTION
# ----------------------------
stopwords = set([
    "the","and","or","to","of","in","a","an","for","with","on","at","by","is","are",
    "was","were","be","this","that","as","it","from","i","you","we","they","their"
])

def extract_keywords(text, top_n=12):
    words = re.findall(r"[a-zA-Z]+", text.lower())
    filtered = [w for w in words if w not in stopwords and len(w) > 2]
    counts = Counter(filtered)
    return [w for w, _ in counts.most_common(top_n)]

# ----------------------------
# FIND FILES
# ----------------------------
resume_file = "Jos_cv.docx"
job_files = sorted(glob.glob("J*.docx"))

if not job_files:
    raise Exception("No J*.docx files found in directory.")

resume_text = read_docx(resume_file)

# ----------------------------
# BUILD TAILORED RESUMES
# ----------------------------
for job_file in job_files:

    job_text = read_docx(job_file)
    keywords = extract_keywords(job_text)

    job_name = os.path.splitext(job_file)[0]

    doc = Document()

    # Title
    doc.add_heading(f"Tailored Resume - {job_name}", level=1)

    # Summary
    doc.add_heading("Professional Summary", level=2)
    doc.add_paragraph(resume_text[:900] + "...")

    # Skills Section (ATS Optimization)
    doc.add_heading("Key Skills Aligned to Job Description", level=2)
    for kw in keywords:
        doc.add_paragraph(f"• {kw}")

    # Optional enhancement section
    doc.add_heading("Professional Fit Summary", level=2)
    doc.add_paragraph(
        "This resume version is optimized to align with the job description "
        "based on extracted skills and keyword relevance."
    )

    # Save file
    output_file = f"tailored_resume_{job_name}.docx"
    doc.save(output_file)

    print(f"Created: {output_file}")

# Re-do the resume for each job to improve match
import docx2txt
import pandas as pd
import glob
import os
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Load resume
resume = docx2txt.process("Jos_cv.docx")

# Dynamically get all job files like J1.docx, J2.docx, ...
job_files = sorted(glob.glob("tailored_resume_J*.docx"))

results = []

for job_file in job_files:
    # Load job description
    job_description = docx2txt.process(job_file)

    # Combine texts
    text = [resume, job_description]

    # Vectorize
    cv = CountVectorizer()
    count_matrix = cv.fit_transform(text)

    # Similarity score
    similarity = cosine_similarity(count_matrix)[0][1] * 100
    similarity = round(similarity, 2)

    # Clean job name (remove .docx)
    job_name = os.path.splitext(job_file)[0]

    results.append({
        "Job": job_name,
        "Match %": similarity
    })

# Create table
df = pd.DataFrame(results)

# Sort by best match
df = df.sort_values(by="Match %", ascending=False).reset_index(drop=True)

print(df)





